/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as ExecutiveIndexRouteImport } from './routes/executive.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as PartnerOnboardingIndexRouteImport } from './routes/partner.onboarding.index'
import { Route as PartnerExecutivesIndexRouteImport } from './routes/partner.executives.index'
import { Route as PartnerEmailConfigIndexRouteImport } from './routes/partner.email-config.index'
import { Route as PartnerDocumentsIndexRouteImport } from './routes/partner.documents.index'
import { Route as PartnerClientsIndexRouteImport } from './routes/partner.clients.index'
import { Route as PartnerAuditIndexRouteImport } from './routes/partner.audit.index'
import { Route as ExecutiveOnboardingIndexRouteImport } from './routes/executive.onboarding.index'
import { Route as ExecutiveDocumentsIndexRouteImport } from './routes/executive.documents.index'
import { Route as ExecutiveClientsIndexRouteImport } from './routes/executive.clients.index'
import { Route as ClientOnboardingIndexRouteImport } from './routes/client.onboarding.index'
import { Route as ClientNotificationsIndexRouteImport } from './routes/client.notifications.index'
import { Route as ClientFilingsIndexRouteImport } from './routes/client.filings.index'
import { Route as PartnerClientsClientIdRouteImport } from './routes/partner.clients.$clientId'
import { Route as ExecutiveClientsClientIdRouteImport } from './routes/executive.clients.$clientId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const ExecutiveIndexRoute = ExecutiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const PartnerOnboardingIndexRoute = PartnerOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerExecutivesIndexRoute = PartnerExecutivesIndexRouteImport.update({
  id: '/executives/',
  path: '/executives/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerEmailConfigIndexRoute = PartnerEmailConfigIndexRouteImport.update({
  id: '/email-config/',
  path: '/email-config/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDocumentsIndexRoute = PartnerDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerClientsIndexRoute = PartnerClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerAuditIndexRoute = PartnerAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => PartnerRoute,
} as any)
const ExecutiveOnboardingIndexRoute =
  ExecutiveOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => ExecutiveRoute,
  } as any)
const ExecutiveDocumentsIndexRoute = ExecutiveDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveClientsIndexRoute = ExecutiveClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ClientOnboardingIndexRoute = ClientOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsIndexRoute =
  ClientNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ClientRoute,
  } as any)
const ClientFilingsIndexRoute = ClientFilingsIndexRouteImport.update({
  id: '/filings/',
  path: '/filings/',
  getParentRoute: () => ClientRoute,
} as any)
const PartnerClientsClientIdRoute = PartnerClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => PartnerRoute,
} as any)
const ExecutiveClientsClientIdRoute =
  ExecutiveClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => ExecutiveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/executive': typeof ExecutiveRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/client/': typeof ClientIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/executive/clients/$clientId': typeof ExecutiveClientsClientIdRoute
  '/partner/clients/$clientId': typeof PartnerClientsClientIdRoute
  '/client/filings/': typeof ClientFilingsIndexRoute
  '/client/notifications/': typeof ClientNotificationsIndexRoute
  '/client/onboarding/': typeof ClientOnboardingIndexRoute
  '/executive/clients/': typeof ExecutiveClientsIndexRoute
  '/executive/documents/': typeof ExecutiveDocumentsIndexRoute
  '/executive/onboarding/': typeof ExecutiveOnboardingIndexRoute
  '/partner/audit/': typeof PartnerAuditIndexRoute
  '/partner/clients/': typeof PartnerClientsIndexRoute
  '/partner/documents/': typeof PartnerDocumentsIndexRoute
  '/partner/email-config/': typeof PartnerEmailConfigIndexRoute
  '/partner/executives/': typeof PartnerExecutivesIndexRoute
  '/partner/onboarding/': typeof PartnerOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/client': typeof ClientIndexRoute
  '/executive': typeof ExecutiveIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/executive/clients/$clientId': typeof ExecutiveClientsClientIdRoute
  '/partner/clients/$clientId': typeof PartnerClientsClientIdRoute
  '/client/filings': typeof ClientFilingsIndexRoute
  '/client/notifications': typeof ClientNotificationsIndexRoute
  '/client/onboarding': typeof ClientOnboardingIndexRoute
  '/executive/clients': typeof ExecutiveClientsIndexRoute
  '/executive/documents': typeof ExecutiveDocumentsIndexRoute
  '/executive/onboarding': typeof ExecutiveOnboardingIndexRoute
  '/partner/audit': typeof PartnerAuditIndexRoute
  '/partner/clients': typeof PartnerClientsIndexRoute
  '/partner/documents': typeof PartnerDocumentsIndexRoute
  '/partner/email-config': typeof PartnerEmailConfigIndexRoute
  '/partner/executives': typeof PartnerExecutivesIndexRoute
  '/partner/onboarding': typeof PartnerOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/executive': typeof ExecutiveRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/client/': typeof ClientIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/executive/clients/$clientId': typeof ExecutiveClientsClientIdRoute
  '/partner/clients/$clientId': typeof PartnerClientsClientIdRoute
  '/client/filings/': typeof ClientFilingsIndexRoute
  '/client/notifications/': typeof ClientNotificationsIndexRoute
  '/client/onboarding/': typeof ClientOnboardingIndexRoute
  '/executive/clients/': typeof ExecutiveClientsIndexRoute
  '/executive/documents/': typeof ExecutiveDocumentsIndexRoute
  '/executive/onboarding/': typeof ExecutiveOnboardingIndexRoute
  '/partner/audit/': typeof PartnerAuditIndexRoute
  '/partner/clients/': typeof PartnerClientsIndexRoute
  '/partner/documents/': typeof PartnerDocumentsIndexRoute
  '/partner/email-config/': typeof PartnerEmailConfigIndexRoute
  '/partner/executives/': typeof PartnerExecutivesIndexRoute
  '/partner/onboarding/': typeof PartnerOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/executive'
    | '/login'
    | '/partner'
    | '/register'
    | '/client/'
    | '/executive/'
    | '/partner/'
    | '/executive/clients/$clientId'
    | '/partner/clients/$clientId'
    | '/client/filings/'
    | '/client/notifications/'
    | '/client/onboarding/'
    | '/executive/clients/'
    | '/executive/documents/'
    | '/executive/onboarding/'
    | '/partner/audit/'
    | '/partner/clients/'
    | '/partner/documents/'
    | '/partner/email-config/'
    | '/partner/executives/'
    | '/partner/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/client'
    | '/executive'
    | '/partner'
    | '/executive/clients/$clientId'
    | '/partner/clients/$clientId'
    | '/client/filings'
    | '/client/notifications'
    | '/client/onboarding'
    | '/executive/clients'
    | '/executive/documents'
    | '/executive/onboarding'
    | '/partner/audit'
    | '/partner/clients'
    | '/partner/documents'
    | '/partner/email-config'
    | '/partner/executives'
    | '/partner/onboarding'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/executive'
    | '/login'
    | '/partner'
    | '/register'
    | '/client/'
    | '/executive/'
    | '/partner/'
    | '/executive/clients/$clientId'
    | '/partner/clients/$clientId'
    | '/client/filings/'
    | '/client/notifications/'
    | '/client/onboarding/'
    | '/executive/clients/'
    | '/executive/documents/'
    | '/executive/onboarding/'
    | '/partner/audit/'
    | '/partner/clients/'
    | '/partner/documents/'
    | '/partner/email-config/'
    | '/partner/executives/'
    | '/partner/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  ExecutiveRoute: typeof ExecutiveRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/executive/': {
      id: '/executive/'
      path: '/'
      fullPath: '/executive/'
      preLoaderRoute: typeof ExecutiveIndexRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/partner/onboarding/': {
      id: '/partner/onboarding/'
      path: '/onboarding'
      fullPath: '/partner/onboarding/'
      preLoaderRoute: typeof PartnerOnboardingIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/executives/': {
      id: '/partner/executives/'
      path: '/executives'
      fullPath: '/partner/executives/'
      preLoaderRoute: typeof PartnerExecutivesIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/email-config/': {
      id: '/partner/email-config/'
      path: '/email-config'
      fullPath: '/partner/email-config/'
      preLoaderRoute: typeof PartnerEmailConfigIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/documents/': {
      id: '/partner/documents/'
      path: '/documents'
      fullPath: '/partner/documents/'
      preLoaderRoute: typeof PartnerDocumentsIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/clients/': {
      id: '/partner/clients/'
      path: '/clients'
      fullPath: '/partner/clients/'
      preLoaderRoute: typeof PartnerClientsIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/audit/': {
      id: '/partner/audit/'
      path: '/audit'
      fullPath: '/partner/audit/'
      preLoaderRoute: typeof PartnerAuditIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/executive/onboarding/': {
      id: '/executive/onboarding/'
      path: '/onboarding'
      fullPath: '/executive/onboarding/'
      preLoaderRoute: typeof ExecutiveOnboardingIndexRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/documents/': {
      id: '/executive/documents/'
      path: '/documents'
      fullPath: '/executive/documents/'
      preLoaderRoute: typeof ExecutiveDocumentsIndexRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/clients/': {
      id: '/executive/clients/'
      path: '/clients'
      fullPath: '/executive/clients/'
      preLoaderRoute: typeof ExecutiveClientsIndexRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/client/onboarding/': {
      id: '/client/onboarding/'
      path: '/onboarding'
      fullPath: '/client/onboarding/'
      preLoaderRoute: typeof ClientOnboardingIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications/': {
      id: '/client/notifications/'
      path: '/notifications'
      fullPath: '/client/notifications/'
      preLoaderRoute: typeof ClientNotificationsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/filings/': {
      id: '/client/filings/'
      path: '/filings'
      fullPath: '/client/filings/'
      preLoaderRoute: typeof ClientFilingsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/partner/clients/$clientId': {
      id: '/partner/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/partner/clients/$clientId'
      preLoaderRoute: typeof PartnerClientsClientIdRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/executive/clients/$clientId': {
      id: '/executive/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/executive/clients/$clientId'
      preLoaderRoute: typeof ExecutiveClientsClientIdRouteImport
      parentRoute: typeof ExecutiveRoute
    }
  }
}

interface ClientRouteChildren {
  ClientIndexRoute: typeof ClientIndexRoute
  ClientFilingsIndexRoute: typeof ClientFilingsIndexRoute
  ClientNotificationsIndexRoute: typeof ClientNotificationsIndexRoute
  ClientOnboardingIndexRoute: typeof ClientOnboardingIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientIndexRoute: ClientIndexRoute,
  ClientFilingsIndexRoute: ClientFilingsIndexRoute,
  ClientNotificationsIndexRoute: ClientNotificationsIndexRoute,
  ClientOnboardingIndexRoute: ClientOnboardingIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface ExecutiveRouteChildren {
  ExecutiveIndexRoute: typeof ExecutiveIndexRoute
  ExecutiveClientsClientIdRoute: typeof ExecutiveClientsClientIdRoute
  ExecutiveClientsIndexRoute: typeof ExecutiveClientsIndexRoute
  ExecutiveDocumentsIndexRoute: typeof ExecutiveDocumentsIndexRoute
  ExecutiveOnboardingIndexRoute: typeof ExecutiveOnboardingIndexRoute
}

const ExecutiveRouteChildren: ExecutiveRouteChildren = {
  ExecutiveIndexRoute: ExecutiveIndexRoute,
  ExecutiveClientsClientIdRoute: ExecutiveClientsClientIdRoute,
  ExecutiveClientsIndexRoute: ExecutiveClientsIndexRoute,
  ExecutiveDocumentsIndexRoute: ExecutiveDocumentsIndexRoute,
  ExecutiveOnboardingIndexRoute: ExecutiveOnboardingIndexRoute,
}

const ExecutiveRouteWithChildren = ExecutiveRoute._addFileChildren(
  ExecutiveRouteChildren,
)

interface PartnerRouteChildren {
  PartnerIndexRoute: typeof PartnerIndexRoute
  PartnerClientsClientIdRoute: typeof PartnerClientsClientIdRoute
  PartnerAuditIndexRoute: typeof PartnerAuditIndexRoute
  PartnerClientsIndexRoute: typeof PartnerClientsIndexRoute
  PartnerDocumentsIndexRoute: typeof PartnerDocumentsIndexRoute
  PartnerEmailConfigIndexRoute: typeof PartnerEmailConfigIndexRoute
  PartnerExecutivesIndexRoute: typeof PartnerExecutivesIndexRoute
  PartnerOnboardingIndexRoute: typeof PartnerOnboardingIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerIndexRoute: PartnerIndexRoute,
  PartnerClientsClientIdRoute: PartnerClientsClientIdRoute,
  PartnerAuditIndexRoute: PartnerAuditIndexRoute,
  PartnerClientsIndexRoute: PartnerClientsIndexRoute,
  PartnerDocumentsIndexRoute: PartnerDocumentsIndexRoute,
  PartnerEmailConfigIndexRoute: PartnerEmailConfigIndexRoute,
  PartnerExecutivesIndexRoute: PartnerExecutivesIndexRoute,
  PartnerOnboardingIndexRoute: PartnerOnboardingIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  ExecutiveRoute: ExecutiveRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
